AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  downloadTwitterPhotos:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: handler.handler
      Runtime: python3.6
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::187551275141:role/lambda_execution_s3_write'
